services:
  backend:
    container_name: backends
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["gunicorn", "auth_backend.wsgi:application", "--bind", "0.0.0.0:5000"]
    environment:
      PG_DATABASE: aser
      PG_USER: admin
      PG_PASSWORD: admin
      PG_HOST: postgres_01
      SECRET_KEY: 1
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/app
    depends_on:
      - postgres_01
    networks:
      - backend


  postgres_01:
    image: postgres
    container_name: postgres_backend
    restart: always
    environment:
      POSTGRES_DB: aser
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: 5432
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge